baseurl: ''
url: 'https://terminaldetransporte.com'
name: Terminal de Transporte
author: Julian Franco
email: info@terminalesdetransporte.com
instagram: https://www.instagram.com/terminaldetransporte/
twitter: https://twitter.com/bloglaterminal

markdown: kramdown

permalink: :slug

plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 9
paginate_path: /blog/page:num/

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []