baseurl: ''
url: 'https://terminaldetransporte.com'
name: 'TerminaldeTransporte.com'
author: terminaldetransporte.com
email: info@terminalesdetransporte.com
instagram: https://www.instagram.com/terminaldetransporte/
twitter: https://twitter.com/bloglaterminal

markdown: kramdown

permalink: :slug

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

collections:
  posts:
    output: true
    permalink: /blog/:slug
  destinos:
    output: true
    permalink: /pasajes/:path
  terminales:
    output: true
    permalink: /:path