# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: 'blog'
public_folder: '/img/blog'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'J-son', name: 'json-post', widget: 'hidden', default: 'true' }
      - { label: 'Fecha', name: 'date', widget: 'datetime' }
      - { label: 'Meta Title', name: 'title', widget: 'string' }
      - { label: 'Meta Description', name: 'description', widget: 'string' }
      - { label: 'Autor', name: 'autor', widget: 'string' }
      - { label: 'H1', name: 'h1', widget: 'string' }
      - { label: 'JPGx600', name: 'jpg', widget: 'image' }
      - { label: 'Mediumx600', name: 'webpm', widget: 'image' }
      - { label: 'Smallx376', name: 'webps', widget: 'image' }
      - { label: 'Alt', name: 'alt', widget: 'string' }
      - { label: 'URL', name: 'permalink', widget: 'string' }
      - { label: 'Intro', name: 'excerpt', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }